#!/bin/bash

set -eu

cd $(dirname $0)
source lib/common.sh

run_stages() {
	local test="$1"
	local stages="$2"
	source "test_$test.sh"
	$tracecmd
	test="./test_$test"

	for s in $stages; do
		$s
	done
}

tracecmd=true
if [ "${1:-}" == "trace" ]; then
	tracecmd="set -x"
	shift
fi

case "${1:-}" in
	cleanup)
		cleanup
		;;
	prepare|connect|test)
		if [ -z "${2:-}" ]; then
			echo "Test name expected" >&2
			exit 1
		fi
		cleanup_handler=true
		run_stages "$2" "$1"
		;;
	run)
		if [ -z "${2:-}" ]; then
			echo "Test name expected" >&2
			exit 1
		fi
		cleanup_handler=cleanup
		run_stages "$2" "prepare connect test cleanup"
		;;
	*)
		echo "Usage:" >&2
		echo "	$0 [trace] prepare|connect|test|cleanup|run <test>" >&2
		exit 1
		;;
esac
