language: c
sudo: required
dist: trusty

notifications:
    email:
        recipients:
            - lsdn-travis@asch.cz
        on_success: change
        on_failure: always

install:
    - sudo apt-get install tcl-dev libmnl-dev libvirt-dev cmake valgrind qemu uthash-dev libjson0-dev libdaemon-dev
    - pwd
    - wget https://rkapl.cz/uploads/lsdn-testenv-3.tar.xz -O testenv.tar.xz
    - echo 'b53ffd6434dd1caf6b252adee6c5d6098a2646cf5c85c0bf7593dbf78f216a9e  testenv.tar.xz'|sha256sum -c
    - tar xf testenv.tar.xz

env:
  global:
    - CTEST_EXT_COLOR_OUTPUT=TRUE
    - CTEST_BUILD_FLAGS=-j4
    - LSDN_VALGRIND=1

script:
    - pwd
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DLARGE_TESTS=OFF -DKERNEL_HEADERS=`pwd`/../headers/include ..
    - make
    - cd test
    - ./run-qemu ../../bzImage ../../rootfs all
