language: c
sudo: required
dist: trusty

notifications:
    email:
        recipients:
            - lsdn-travis@asch.cz
        on_success: change
        on_failure: always

install:
    - sudo apt-get install tcl-dev libmnl-dev libvirt-dev cmake valgrind qemu uthash-dev
    - pwd
    - wget https://rkapl.cz/uploads/lsdn-testenv-2.tar.xz -O testenv.tar.xz
    - echo 'b2f4c30d41b82801d034e7b8aeac5266d43aadf4940a0e5f6da1db5d5e7a1cda  testenv.tar.xz'|sha256sum -c
    - tar xf testenv.tar.xz

env:
  global:
    - CTEST_EXT_COLOR_OUTPUT=TRUE
    - CTEST_BUILD_FLAGS=-j4
    - LSDN_VALGRIND=1

script:
    - pwd
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DLARGE_TESTS=OFF -DKERNEL_HEADERS=`pwd`/../headers/include ..
    - make
    - cd test
    - ./run-qemu ../../bzImage ../../rootfs all
