language: c
dist: trusty

notifications:
    email:
        recipients:
            - lsdn-travis@asch.cz
        on_success: change
        on_failure: always

addons:
    apt:
        packages:
            - tcl-dev
            - libmnl-dev
            - libvirt-dev
            - cmake
            - realpath
            - qemu uthash-dev
            - libjson0-dev
            - libdaemon-dev
            - isc-dhcp-server
            - isc-dhcp-client

install:
    - wget https://rkapl.cz/uploads/lsdn-testenv-3.tar.xz -O testenv.tar.xz
    - echo '12359db1c67cad9be6ab5b7bfe22e1d9e0547b8427359fd8644e2746ef10767e  testenv.tar.xz'|sha256sum -c
    - tar xf testenv.tar.xz

env:
  global:
    - CTEST_EXT_COLOR_OUTPUT=TRUE
    - CTEST_BUILD_FLAGS=-j4
    - LSDN_VALGRIND=1

script:
    - pwd
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DLARGE_TESTS=OFF -DKERNEL_HEADERS=`pwd`/../headers/include ..
    - make
    - cd test
    - ./run-qemu ../../bzImage / all
