#!/bin/bash

echo Preparing environment ...
mount -t proc none /proc
mount -t sysfs none /sys
mkdir -p /run/netns
mount -t tmpfs none /run/netns
echo OK

echo -n 'Running '
cat qemu/work
. qemu/work

poweroff -f
